### ISSUE TITLE
Remove redundant call to abs in metal shader

### ISSUE THREAD

**Issue by olemarius90** [palmerc/Beamformer#1]
The following code is taken from line 118 to 120 in https://github.com/palmerc/Beamformer/blob/master/SmartWave/Common/Metal/Beamformer.metal

`            
float distanceX = abs(pixelPositionXInMillimeters - elementPositionXInMillimeters);
float receiveAperture = pixelPositionZInMillimeters / fNumber;
float distance = abs(distanceX);
`

However, distanceX and distance should always be the same. So you can get rid of distance and just use distanceX.

**Comment by olemarius90** [comment]
Why does it squash the code together?

**Comment by palmerc** [comment]
Squash? you mean put it on the same line?

**Comment by olemarius90** [comment]
Yes, in this tread though.

**Comment by palmerc** [comment]
That line is obviously an artefact of development and essentially does nothing.

**Comment by olemarius90** [comment]
Hehe, I know. No big deal. I was just considering if we should list some code. But I think not. I also use the code to better describe the beamforming process as the reviewers asked for.

**Comment by palmerc** [comment]
We can create a PR and then patch this
